### ISSUE TITLE
Segment Validation test never completes

### ISSUE THREAD

**Issue by nicholas-fr** [Dash-Industry-Forum/DASH-IF-Conformance#602]
Currently the Segment Validation test never completes when running it via https://conformance.dashif.org/

For example, using:
https://dash.akamaized.net/WAVE/vectors/cfhd_sets/15_30_60/t1/2022-10-17/stream.mpd

With additional tests:
Segment Validation
CMAF
CTA WAVE

The following is shown and remains this way indefinitely (hours later):
![image](https://user-images.githubusercontent.com/9865551/199520394-3d3c3dc9-93eb-482e-bcac-a925e5d213de.png)

**Comment by dsilhavy** [comment]
probably related to #604

**Comment by dsilhavy** [comment]
We merged #611 can you please check if this fixes your problem

**Comment by nicholas-fr** [comment]
https://beta.conformance.dashif.org is currently unavailable (503).

Issue still present with https://conformance.dashif.org/

**Comment by dsilhavy** [comment]
Still present on https://beta.conformance.dashif.org/. Probably related to processes that are not terminating, @Phencys is already addressing these issues in refactor phase. To be evaluated against version 2.1.0 and 2.2.0

**Comment by Phencys** [comment]
There are quite a few bugst that could be related to this, and some of them are probably due to issues with the segment validator.

The pull request above sets a maximum running time for the segment validator, and exists upon various health issues as described in it.

On top of this, there are also some known-issues in the current Front-End, that are hard to pin down to a specific reason.

These issues should however not be applicable anymore once the new UI is released

**Comment by rbouqueau** [comment]
My latest batch of commits on the SegmentValidator should fix this.

**Comment by dsilhavy** [comment]
Fixed on https://staging.conformance.dashif.org/Conformance-Frontend-JCCP/#home , output is now generated
