### ISSUE TITLE
Observed a "SyntaxError: Unexpected end of JSON input" for the mpd that contains Role and Accessibility elements when we enable the "DVB (2018 xsd)" option on the conformance tool.

### ISSUE THREAD

**Issue by Ramajayadevi** [Dash-Industry-Forum/DASH-IF-Conformance#707]
Below is the mpd we tried to validate in the dash conformance tool when we enable "DVB (2018 xsd)" option , but the tool is not able to parse the mpd and says "SyntaxError: Unexpected end of JSON input" error. 

When we dont enable "DVB (2018 xsd)" option while validating the mpd in the conformance tool, then the mpd validation is passed without syntax error.
[visually_impaired_with_both_mix_type0_1.txt](https://github.com/user-attachments/files/16597166/visually_impaired_with_both_mix_type0_1.txt)

Here is the conformance tool we used to validate this mpd:
https://conformance.dashif.org/

When we refer the issues reported to the dash forum, found this bug which is related to the same error, but this error is not resolved.
https://github.com/Dash-Industry-Forum/DASH-IF-Conformance/issues/677

Could you please check and provide the feedback.

**Comment by Ramajayadevi** [comment]
[visually_impaired_with_both_mix_type0_1.txt](https://github.com/user-attachments/files/16597151/visually_impaired_with_both_mix_type0_1.txt)

attached the manifest file here

Here is the conformance tool we used to validate this mpd:
https://conformance.dashif.org/

When we refer the issues reported to the dash forum, found this bug which is related to the same error, but this error is not resolved.
https://github.com/Dash-Industry-Forum/DASH-IF-Conformance/issues/677

Could you please check and provide the feedback.

**Comment by Phencys** [comment]
This issue was triggered by a divergence of options between the CLI and REST api's, in combination with the upgrade to PHP8.x

Should be resolved on https://staging.conformance.dashif.org/

**Comment by kjerbi** [comment]
Hi @Phencys ,
Thanks @Ramajayadevi  for raising the issue.
I am still seeing the problem even with the staging link. I confirm the issue appears when using dvb2018.
Any updates?
Manifest attached
[manifest_dvb2018.zip](https://github.com/user-attachments/files/16996812/manifest_dvb2018.zip)

Many thanks in advance

**Comment by Ramajayadevi** [comment]
Hi @kjerbi,

Yes, Am also still seeing the issue with the staging link which was shared here.

Thanks,
Ramajayadevi.

**Comment by Phencys** [comment]
Hello @kjerbi and @Ramajayadevi 

Thanks for the update on the issue and the extra manifest to debug.

Apparently there were a lot of surpressed warnings in the code, and some code that used to be valid before the PHP8 upgrade now failed silently (but triggering other issues)

The version on staging supports both updated manifests now. Can either of you confirm?

**Comment by Ramajayadevi** [comment]
Hi @Phencys ,

Thanks for the response.

Still with the same staging tool, am seeing an error.

Thanks,
Ramajayadevi.

**Comment by Phencys** [comment]
Some extra context on the bug:
This message is given whenever the PHP code crashes. Independent of where or how, if there is an issue with the PHP code itself, this message is displayed in the interface. Because PHP code is only 'really' checked at runtime, a lot of the issue only arise if we have specific enough scenario's.

Looking at the logs on the staging environment, I can trace back one error, but it seems related to segment analysis.

I have tried to fix it, but this is quite tricky without the actual segments. @Ramajayadevi can you please check for me
1. If the analysis works for you when the segments are not validated
2. If the analysis now works with segment validation enabled?

If step 2 is still a no, can you possibly provide us a couple of the segments in the stream, to allow better debugging?

**Comment by kjerbi** [comment]
@Phencys 
many thanks for th quick reaction!
I confirm my manifest now does not have the "unexpected end of json" issue.

Kind regards
Khaled

**Comment by Phencys** [comment]
I have created a new issue (#708) to track progress on the bigger picture behind this issue.

It will be picked up as part of the next release.

**Comment by Ramajayadevi** [comment]
Hi @Phencys ,

I have checked

Without enabling the "Segment validation" option on the staging link and i can see my mpd has been validated without syntax error.
With enabling the "Segment validation" option, i can see the same syntax error.

Thanks,
Ramajayadevi.

**Comment by Phencys** [comment]
This should no longer occur as of v.3.0.0

If the issues do still occur, please re-open with more reproduction information.
